# AI Polling Data Loading Script
# Generated by ai-polling pipeline on 2025-07-06 20:33:40

library(readr)
library(dplyr)
library(lubridate)

# Load polling data
load_polling_data_data <- function(format = "csv") {
  
  if (format == "csv") {
    # Load from CSV (most compatible)
    data <- read_csv("test_output_diagnostic/polling_data_20250706_203339.csv", show_col_types = FALSE)
    
    # Convert date columns
    if ("fieldwork_date" %in% colnames(data)) {
      data$fieldwork_date <- as.Date(data$fieldwork_date)
    }
    
    # Convert to factors for better R analysis
    factor_cols <- c("category", "survey_organisation", "country")
    for (col in factor_cols) {
      if (col %in% colnames(data)) {
        data[[col]] <- as.factor(data[[col]])
      }
    }
    
    return(data)
    
  } else if (format == "rds") {
    # Load from RDS (native R format)
    if (file.exists("test_output_diagnostic/polling_data_20250706_203339.rds")) {
      return(readRDS("test_output_diagnostic/polling_data_20250706_203339.rds"))
    } else {
      warning("RDS file not found, falling back to CSV")
      return(load_polling_data_data("csv"))
    }
  }
}

# Convenience function to load latest data
load_latest_polling_data <- function() {
  return(load_polling_data_data())
}

# Filter functions for common analyses
get_ai_regulation_questions <- function(data = NULL) {
  if (is.null(data)) data <- load_latest_polling_data()
  return(data %>% filter(category == "AI_Regulation"))
}

get_questions_by_organization <- function(org, data = NULL) {
  if (is.null(data)) data <- load_latest_polling_data()
  return(data %>% filter(survey_organisation == org))
}

get_questions_by_country <- function(country, data = NULL) {
  if (is.null(data)) data <- load_latest_polling_data()
  return(data %>% filter(country == country))
}

# Summary function
summarize_polling_data <- function(data = NULL) {
  if (is.null(data)) data <- load_latest_polling_data()
  
  cat("=== AI POLLING DATA SUMMARY ===\n")
  cat("Total questions:", nrow(data), "\n")
  cat("Organizations:", length(unique(data$survey_organisation)), "\n")
  cat("Countries:", length(unique(data$country)), "\n")
  cat("Date range:", min(data$fieldwork_date, na.rm = TRUE), "to", 
      max(data$fieldwork_date, na.rm = TRUE), "\n")
  
  cat("\nQuestions by category:\n")
  print(table(data$category))
  
  cat("\nQuestions by organization:\n")
  print(table(data$survey_organisation))
  
  return(invisible(data))
}

# Example usage:
# data <- load_latest_polling_data()
# ai_reg <- get_ai_regulation_questions()
# summarize_polling_data()

cat("AI Polling data loading functions ready!\n")
cat("Use load_latest_polling_data() to load the data\n")
cat("Use summarize_polling_data() for a quick overview\n")
